detectors:
  - importDeclaration
  - exportDeclaration
  - importCallExpression
  - requireCallExpression
  - requireResolveCallExpression
  - typescriptImportEqualsDeclaration
  - typescriptImportType
specials:
  - bin
  - eslint
  - istanbul
  - mocha
  - prettier
