language: node_js
node_js:
  - '10'
  - '12'
before_install:
  - npm install -g coveralls
after_success:
  - coveralls < ./coverage/lcov.info
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-.*)?$/
